[com.google.android.dialer]
ro.product.model=Pixel 9 Pro XL
ro.product.manufacterer=Google
ro.product.brand=google
ro.product.device=komodo
ro.build.fingerprint=google/komodo/komodo:15/AP1A.250905.001/12345678:user/release-keys

[com.google.android.photos]
ro.product.model=Pixel 9 Pro XL
ro.product.manufacterer=Google
ro.product.brand=google
ro.product.device=komodo
ro.build.fingerprint=google/komodo/komodo:15/AP1A.250905.001/12345678:user/release-keys
