import org.apache.tools.ant.filters.FixCrLfFilter
import org.apache.tools.ant.filters.ReplaceTokens
import org.gradle.api.file.DuplicatesStrategy
import java.security.MessageDigest

plugins {
    id 'com.android.library'
}

apply from: file(rootProject.file('module.gradle'))

def buildDir1 = "$rootDir/beta/build"
def buildDir2 = "$rootDir/beta/.cxx"
def buildDir3 = "$rootDir/beta/zygisk/build"
def buildDir4 = "$rootDir/build"

android {
    namespace 'com.pixelify.next.beta.zygisk'
    compileSdk target_sdk
    ndkVersion rootProject.ext.ndkVersion
    defaultConfig {
        minSdk min_sdk
        targetSdk target_sdk
        externalNativeBuild {
            // ndkBuild {
            //     path("zygisk/src/main/cpp/external/Android.mk")
            // }
            cmake {
                arguments "-DMODULE_NAME:STRING=$moduleLibraryName"
                cppFlags "-std=gnu++17" // Dowgrade for zygisk v2
            }
        }
        ndk {
          abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }
    buildFeatures {
        prefab false
    }
    externalNativeBuild {
        cmake {
            path "zygisk/src/main/cpp/CMakeLists.txt"
        }
    }
}

afterEvaluate {
    android.libraryVariants.forEach { variant ->
        def variantCapped = variant.name.capitalize()
        def variantLowered = variant.name.toLowerCase()
	
	def betaPath = "$rootDir/beta"
        def zipName = "${magiskModuleId.replace('_', '-')}-BETA-${moduleVersion}.zip"
        def zipNamenovk = "${magiskModuleId.replace('_', '-')}-BETA-${moduleVersion}-no-VK.zip"
        def magiskDir = file("$outDir/magisk_module_beta_$variantLowered")
        def templatePath = "$betaPath/module"
        def types = [Instance1: 'arm64-v8a', Instance2: 'armeabi-v7a',Instance3: 'x86',Instance4: 'x86_64']

        task("prepareMagiskFiles${variantCapped}", type: Sync) {
            duplicatesStrategy = DuplicatesStrategy.WARN
            
            dependsOn("assemble$variantCapped")
            def nativeOutDir = file("$rootDir/riru/build/intermediates/cmake/$variant.name/obj")

            into magiskDir
            from(templatePath) {
                exclude 'module.prop', 'module/files/system'
            }
            from(templatePath) {
                include 'module.prop'
                expand([
                        id          : magiskModuleId,
                        name        : moduleName,
                        version     : moduleVersion,
                        versionCode: moduleVersionCode.toString(),
                        author      : moduleAuthor,
                        description: moduleDescription,
                        volType: "1",
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }
            types.each { instance, resourceDir ->
                def libSourceDir = "$buildDir/intermediates/stripped_native_libs/$variantLowered/strip${variantCapped}DebugSymbols/out/lib/$resourceDir"
                def archSuffix = (resourceDir == 'arm64-v8a') ? '-64.so' : '-32.so'
                from(libSourceDir) {
                    into 'lib/zygisk'
                    include "**/libpixelify-next.so" 
                    rename 'libpixelify-next.so', "${resourceDir}.so"
                }
                from(libSourceDir) {
                    into 'lib/zygisk'
                    include "**/libpixelify-next-camera.so"
                    rename { String fn -> fn.replace(".so", "${archSuffix}") }
                }
                from(libSourceDir) {
                    into 'lib/zygisk'
                    include "**/libpixelify-next-photos.so"
                    rename { String fn -> fn.replace(".so", "${archSuffix}") }
                }
                from(libSourceDir) {
                    into 'lib/zygisk_tensor'
                    include "**/libpixelify-next-tensor.so"
                    rename 'libpixelify-next-tensor.so', "${resourceDir}.so"
                }
            }

            doLast {
                copy {
                    from "$nativeOutDir"
                    into "$magiskDir/lib/riru"
                    exclude "**/*.txt" , "**/libpixelify-next-tensor.so"
                }
                copy {
                    from "$nativeOutDir"
                    into "$magiskDir/lib/riru_tensor"
                    exclude "**/*.txt" , "**/libpixelify-next.so"
                    rename "libpixelify-next-tensor.so" , "$variant.name"
                }
            }
        }

    task("novk${variantCapped}", type: Sync) {
            duplicatesStrategy = DuplicatesStrategy.WARN
            
            dependsOn("assemble$variantCapped")
            def nativeOutDir = file("$rootDir/riru/build/intermediates/cmake/$variant.name/obj")

            into magiskDir
            from(templatePath) {
                exclude 'module.prop', 'module/files/system'
            }
            from(templatePath) {
                include 'module.prop'
                expand([
                        id          : magiskModuleId,
                        name        : moduleName,
                        version     : moduleVersion,
                        versionCode: moduleVersionCode.toString(),
                        author      : moduleAuthor,
                        description: moduleDescription,
                        volType: "0",
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }
            types.each { instance, resourceDir ->
                def libSourceDir = "$buildDir/intermediates/stripped_native_libs/$variantLowered/strip${variantCapped}DebugSymbols/out/lib/$resourceDir"
                def archSuffix = (resourceDir == 'arm64-v8a') ? '-64.so' : '-32.so'
                from(libSourceDir) {
                    into 'lib/zygisk'
                    include "**/libpixelify-next.so"
                    rename 'libpixelify-next.so', "${resourceDir}.so"
                }
                from(libSourceDir) {
                    into 'lib/zygisk'
                    include "**/*camera.so", "**/*photos.so"
                    rename { String fn -> fn.replace(".so", "${archSuffix}") }
                }
                from(libSourceDir) {
                    into 'lib/zygisk_tensor'
                    include "**/libpixelify-next-tensor.so"
                    rename 'libpixelify-next-tensor.so', "${resourceDir}.so"
                }
            }

            doLast {
		filesMatching('**/module.prop') {
			filter { String line ->
			    if (line.contains('DEVICE_USES_VOLUME_KEY')) {
				return line.replaceAll('DEVICE_USES_VOLUME_KEY\\s*=\\s*1', 'DEVICE_USES_VOLUME_KEY=0')
			    }
			    return line
			}
		    }
                copy {
                    from "$nativeOutDir"
                    into "$magiskDir/lib/riru"
                    exclude "**/*.txt" , "**/libpixelify-next-tensor.so"
                }
                copy {
                    from "$nativeOutDir"
                    into "$magiskDir/lib/riru_tensor"
                    exclude "**/*.txt" , "**/libpixelify-next.so"
                    rename "libpixelify-next-tensor.so" , "libpixelify.so"
                }
            }
        }

        task("zip${variantCapped}", type: Zip) {
            dependsOn("prepareMagiskFiles${variantCapped}")
            from magiskDir
            archiveFileName = zipName
            destinationDirectory = outDir
        }
        task("buildMosey", type: Exec) {
            commandLine "${rootDir}/build_mosey.sh"
        }
        task("novkzip${variantCapped}", type: Zip) {
            dependsOn("zip${variantCapped}")
            dependsOn("novk${variantCapped}")
            tasks.findByName("novk${variantCapped}").mustRunAfter "zip${variantCapped}"
            from magiskDir
            archiveFileName = zipNamenovk
            destinationDirectory = outDir
            doLast {
                delete {
                    from "$outDir"
                    include "config.prop"
                }
                copy {
                    from "$templatePath"
                    into "$outDir"
                    include "config.prop"
                }
            }           
        }

        task("push${variantCapped}", type: Exec) {
            dependsOn("zip${variantCapped}")
            workingDir outDir
            commandLine android.adbExecutable, "push", zipName, "/data/local/tmp/"
        }

        task("flashMagisk${variantCapped}", type: Exec) {
            dependsOn("push${variantCapped}")
            commandLine android.adbExecutable, "shell", "su", "-c",
                    "magisk --install-module /data/local/tmp/${zipName}"
        }
        
        task("flashKsu${variantCapped}", type: Exec) {
            dependsOn("push${variantCapped}")
            commandLine "adb", "shell", "su", "-c", "ksud module install /data/local/tmp/${zipName}"
        }

        task("reboot${variantCapped}", type: Exec) {
            dependsOn("flash${variantCapped}")
            commandLine android.adbExecutable, "shell", "reboot"
        }

        variant.assembleProvider.get().finalizedBy("novkzip${variantCapped}")
    }
    
    task("cleanDir", type: Delete) { 
            delete buildDir1, buildDir2, buildDir3, buildDir4
        }
}
