name: Pixelify Next BETA
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Build untested module versions'
        required: true
        type: string
      target_branch:
        description: 'Select the version to build'
        required: true
        type: choice
        options:
          - STABLE
          - BETA
        default: 'BETA'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
        
    - name: Setup Java JDK
      uses: actions/setup-java@v5.1.0
      with:
          distribution: 'temurin'
          java-version: '17'

    - name: Make Gradlew executable
      run: chmod +x gradlew
      
    - name: Build
      run: ./gradlew build
    - name: Verify Artifact Files Exist
      run: |
          echo "Listing contents of the 'out/' directory:"
          ls -R out/   
    - name: Find and Upload Artifacts
      uses: actions/upload-artifact@v4
      with: 
          name: Build Objects
          path: |
            out/Pixelify*.zip
            out/config.prop
            
         
